### ISSUE TITLE
Windows 11 PermissionError when generating temp svf

### ISSUE THREAD

**Issue by Berzerkula** [roscopeco/atfprog-tools#2]
`PS C:\Users\kb0iic\Downloads> atfu program -d ATF1508 -f .\T030_Glue.jed
ERASE-1   : 51660b [00:12, 4245.08b/s]
Traceback (most recent call last):
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python310\Scripts\atfu.exe\__main__.py", line 7, in <module>
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python310\lib\site-packages\atfu\command.py", line 15, in main
    args.func(args)
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python310\lib\site-packages\atfu\program.py", line 21, in handler
    xsvf_files = _process_input_files(args.device, args.filename, output)
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python310\lib\site-packages\atfu\program.py", line 31, in _process_input_files
    return [_process_input_file(device, result_file, output) for result_file in files]
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python310\lib\site-packages\atfu\program.py", line 31, in <listcomp>
    return [_process_input_file(device, result_file, output) for result_file in files]
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python310\lib\site-packages\atfu\program.py", line 36, in _process_input_file
    return _process_input_svf(output, _process_input_jed(output, device, file))
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python310\lib\site-packages\atfu\program.py", line 58, in _process_input_svf
    infile = open(inname, "r")
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\kb0iic\\AppData\\Local\\Temp\\atfu-temp-1mfzddsi.svf'`

Attempted to search a possible fix. Get the same when running as Administrator. WinVer 23H2 (OS Build 22631.3447)

I've checked AppData\Local\Temp and User has full control. Maybe something in the way inname, "r" is working for svf temp?

**Comment by Berzerkula** [comment]
Updated to Python 3.12.3 and seems to persist:

`atfu program -d ATF1508 -f .\T030_Glue.jed
ERASE-1   : 51660b [00:12, 4245.17b/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python312\Scripts\atfu.exe\__main__.py", line 7, in <module>
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python312\Lib\site-packages\atfu\command.py", line 15, in main
    args.func(args)
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python312\Lib\site-packages\atfu\program.py", line 21, in handler
    xsvf_files = _process_input_files(args.device, args.filename, output)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python312\Lib\site-packages\atfu\program.py", line 31, in _process_input_files
    return [_process_input_file(device, result_file, output) for result_file in files]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python312\Lib\site-packages\atfu\program.py", line 36, in _process_input_file
    return _process_input_svf(output, _process_input_jed(output, device, file))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kb0iic\AppData\Local\Programs\Python\Python312\Lib\site-packages\atfu\program.py", line 58, in _process_input_svf
    infile = open(inname, "r")
             ^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\kb0iic\\AppData\\Local\\Temp\\atfu-temp-opohbh7m.svf'`

**Comment by roscopeco** [comment]
Suspect possible path issue, will investigate 🤔

**Comment by roscopeco** [comment]
Fixed and released to pip, version `2024.1012`. Thanks again for the report @Berzerkula 🤩
