### ISSUE TITLE
Linux system with Python 3.10.2 unable to program with atfu

### ISSUE THREAD

**Issue by Berzerkula** [roscopeco/atfprog-tools#3]
Custom linux from scratch build with 5.18.19 kernel and Python 3.10.2. Looks like something strange with svf.

`atfu program -d ATF1508 -f T030_Glue.jed
ERASE-1   : 51660b [00:12, 4244.86b/s]
Traceback (most recent call last):
  File "/usr/bin/atfu", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/atfu/command.py", line 15, in main
    args.func(args)
  File "/usr/lib/python3.10/site-packages/atfu/program.py", line 21, in handler
    xsvf_files = _process_input_files(args.device, args.filename, output)
  File "/usr/lib/python3.10/site-packages/atfu/program.py", line 31, in _process_input_files
    return [_process_input_file(device, result_file, output) for result_file in files]
  File "/usr/lib/python3.10/site-packages/atfu/program.py", line 31, in <listcomp>
    return [_process_input_file(device, result_file, output) for result_file in files]
  File "/usr/lib/python3.10/site-packages/atfu/program.py", line 36, in _process_input_file
    return _process_input_svf(output, _process_input_jed(output, device, file))
  File "/usr/lib/python3.10/site-packages/atfu/program.py", line 60, in _process_input_svf
    return svf2xsvf(output=output, infile=infile)
  File "/usr/lib/python3.10/site-packages/atfu/converter/svf2xsvf.py", line 522, in svf2xsvf
    bits = makeBitArray(tokVal, length)
  File "/usr/lib/python3.10/site-packages/atfu/converter/svf2xsvf.py", line 302, in makeBitArray
    tokLn,
NameError: name 'tokLn' is not defined`

**Comment by roscopeco** [comment]
Thanks for the report! Are you able to link the .jed file you’re seeing this issue with please and I’ll try to reproduce and get it fixed 🙂

**Comment by roscopeco** [comment]
Reproducible with the same source as #4 if no test vectors are compiled

**Comment by roscopeco** [comment]
**Quick fix**: reintroduce global `tokLn` and `inputFilename` to `svf2xsvf.py`; This is masking another issue in the source `.svf` - likely an incorrect vector size.

**Long term fix**: We should rewrite `svf2xsvf.py` - it is quite poorly architected.

**Comment by roscopeco** [comment]
Suspect underlying cause is #5

**Comment by roscopeco** [comment]
Thanks again for the report @Berzerkula , investigation for this also uncovered an underlying issue (#5 ).

Both should now be fixed and released to pypi. Please upgrade with `pip install little-atf-programmer --upgrade` when convenient.
